In [12]:
import numpy as np 
def save_numpy_array(data,filename=""):
    path = '/Users/paul.tgr/aPavel/VAE_diploma/diploma_scripts/filters/saved_metrics/'
    np.savetxt(path + filename, data, delimiter=',')

def load_numpy_array(filename=""):
    path = '/Users/paul.tgr/aPavel/VAE_diploma/diploma_scripts/filters/saved_metrics/'
    return np.loadtxt(path + filename, delimiter=',')

In [13]:
save_numpy_array(a,"a.csv")
b = load_numpy_array("a.csv")
# print the array
print(b)

[[ 1.  2.  3.  4.  5.  7.  2.  0.]
 [ 1.  2.  3.  4.  5.  7.  2.  0.]
 [ 1.  2.  3.  4.  5.  7.  2.  0.]
 [ 1.  2.  3.  4. 56.  7.  2.  0.]]
